services:
  draftosurus_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: draftosaurus-app
    ports:
      - "3500:80"
    depends_on:
      - database
    networks:
      - netcrudapp

  database:
    image: mariadb
    container_name: Drafto-db
    environment:
      MYSQL_ROOT_PASSWORD: Abgames123@
      MYSQL_DATABASE: Draftosaurus
      MYSQL_USER: abgames
      MYSQL_PASSWORD: MariahCarey321.
    ports:
      - "33060:3306"
    networks:
      - netcrudapp
    volumes:
      - db-volume:/var/lib/mysql
      - ./db/draftosaurus.sql:/docker-entrypoint-initdb.d/draftosaurus.sql

volumes:
  db-volume:

networks:
  netcrudapp:
